import Head from "next/head";
import CartNotification from "../components/CartNotification";
import { useAppContext } from "../context/AppContext";
import { Button } from "@chakra-ui/react";
import Header from "../components/Header";

export default function Home() {
  const { isCartNotification, setIsCartNotification } = useAppContext();

  const toggleCartNotification = () => {
    setIsCartNotification(!isCartNotification);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col static items-center h-screen min-w-[375px] ">
        <Header />
        <div className="h-5/6 ">
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 px-8">
            <div className="">
              <img
                src="https://cdn.shopify.com/s/files/1/0616/7448/8046/products/Artek-85-Anniversary-Poster-Karoliina-Hellberg_600x.jpg?v=1666997421"
                alt="test image"
                className="object-fill w-full"
              />
              <div className="flex flex-row justify-between pt-2 font-light">
                <div>
                  <p>Artek 85 Anniversary Poster, Karoliina Hellberg</p>
                </div>
                <div>$70</div>
              </div>
            </div>
            <div>
              <img
                src="https://cdn.shopify.com/s/files/1/0616/7448/8046/products/DSCF2100_360x.jpg?v=1664841529"
                alt="test image 2"
                className="object-fill w-full"
              />
              <div className="flex flex-row justify-between pt-2 font-light">
                <div>
                  <p>Rollbahn Classic Spiral Notebook Available in 4 Colours</p>
                </div>
                <div>$26</div>
              </div>
            </div>
            <div>
              <img
                src="https://cdn.shopify.com/s/files/1/0616/7448/8046/products/original-267_493x.jpg?v=1642792237"
                alt="test image 3"
                className="object-fill w-full"
              />
              <div className="flex flex-row justify-between pt-2 font-light">
                <div>
                  <p>Allex Scissors Available in 2 Colors</p>
                </div>
                <div>$35</div>
              </div>
            </div>
            <div>
              <img
                src="https://cdn.shopify.com/s/files/1/0616/7448/8046/products/SORT-Vancouver-Design-Store-22_0cdeb552-4161-432f-8607-30391cf38453_493x.jpg?v=1642792222"
                alt="test image 2"
                className="object-fill w-full"
              />
              <div className="flex flex-row justify-betweenpt-2 font-light">
                <div>
                  <p>Rollbahn Classic Spiral Notebook Available in 4 Colours</p>
                </div>
                <div>$26</div>
              </div>
            </div>
          </div>
          <Button onClick={() => toggleCartNotification()}>Sidepanel</Button>
        </div>

        <CartNotification />
      </main>
    </>
  );
}
