import Head from "next/head";
import Header from "../components/Header";
import ProductCard from "../components/ProductCard";
import { config } from "../constants/constants";

export const getStaticProps = async () => {
  const URL = config.url;
  const res = await fetch(`${URL}/api/products/`);
  const data = await res.json();

  return {
    props: { products: data },
  };
};

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>
          Gridstore - Design Store in Montreal, Canada — Design Books,
          Stationery and Home Goods
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col static items-center h-screen min-w-[375px] ">
        <Header />

        <div className="h-5/6 ">
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 px-8">
            {products.products.map((product, index) => {
              return <ProductCard product={product} index={index} />;
            })}
          </div>
        </div>
      </main>
    </>
  );
}
