import Head from "next/head";
import CartNotification from "../components/CartNotification";
import { useAppContext } from "../context/AppContext";
import { Button } from "@chakra-ui/react";
import Header from "../components/Header";
import ProductCard from "../components/ProductCard";
import Link from "next/link";

export const getStaticProps = async () => {
  const res = await fetch("http://localhost:4000/api/products/");
  const data = await res.json();

  return {
    props: { products: data },
  };
};

export default function Home({ products }) {
  const { isCartNotification, setIsCartNotification } = useAppContext();

  const toggleCartNotification = () => {
    setIsCartNotification(!isCartNotification);
  };

  return (
    <>
      <Head>
        <title>
          Gridstore -Design Store in Montreal, Canada — Design Books, Stationery
          and Home Goods{" "}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col static items-center h-screen min-w-[375px] ">
        <Header />

        <div className="h-5/6 ">
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 px-8">
            {products.products.map((product, index) => {
              return <ProductCard product={product} index={index} />;
            })}
          </div>

          <Button onClick={() => toggleCartNotification()}>Sidepanel</Button>
        </div>

        <CartNotification />
      </main>
    </>
  );
}
